id: P000711
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS17156
  title: གཞི་བདག་རྟེན་ལ་བཀོལ་བ་དང་བླ་མ་དྲག་པོའི་རྒྱུན་ཁྱེར།
  author: ''
  volumes:
    719baa33c8524c93be18c6e2e8a22dd0:
      image_group_id: I8LS17172
      title: ''
      volume_number: 1
      total_pages: 534
      base_file: v001.txt
