id: IF766C5AF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T04:38:47+00:00'
last_modified: '2022-06-07T12:43:22.684527+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17156
  title: གཞི་བདག་རྟེན་ལ་བཀོལ་བ་དང་བླ་མ་དྲག་པོའི་རྒྱུན་ཁྱེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4668':
      image_group_id: I8LS17172
      title: ''
      total_pages: 534
      order: 1
      base_file: 4668.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
